# Generated by Django 5.2.8 on 2025-12-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketmaster', '0002_rename_user_usera_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('eventId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('actName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('stateCode', models.CharField(max_length=2)),
                ('photo', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
    ]
