# Generated by Django 5.2.8 on 2025-12-06 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticketmaster', '0003_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='dateString',
            field=models.CharField(default='Date TBD', max_length=100),
        ),
        migrations.AddField(
            model_name='events',
            name='timeString',
            field=models.CharField(default='Time TBD', max_length=100),
        ),
        migrations.AlterField(
            model_name='likes',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticketmaster.events'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ticketmaster.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
